# Generated by Django 6.0 on 2025-12-23 13:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_player', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='mp3_file',
            field=models.FileField(upload_to='songs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3'])]),
        ),
    ]
