# Generated by Django 6.0 on 2025-12-23 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_player', '0002_alter_song_mp3_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='album',
        ),
        migrations.RemoveField(
            model_name='song',
            name='release_date',
        ),
    ]
