# Generated by Django 6.0 on 2025-12-23 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_player', '0003_remove_song_album_remove_song_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='songs', to='music_player.artist'),
        ),
    ]
