# Generated by Django 6.0 on 2025-12-23 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_player', '0007_alter_artist_photo_alter_song_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='cover_image',
            field=models.ImageField(null=True, upload_to='media/covers/'),
        ),
    ]
